### ISSUE TITLE
Icon is not exported for macOS/Windows

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#359]
Gideros settings:
<img width="594" alt="gideros" src="https://user-images.githubusercontent.com/4493302/36931674-83554b7a-1efe-11e8-93b1-5aa1fd88b3e5.png">

Windows:
![windows](https://user-images.githubusercontent.com/4493302/36931673-832dfa34-1efe-11e8-8e1c-3e72ecee6213.PNG)

macOS:
<img width="783" alt="macos" src="https://user-images.githubusercontent.com/4493302/36931675-837e78c4-1efe-11e8-8df0-9d8a0a6c7f42.png">

**Comment by totebo** [comment]
Still relevant. The Gideros icon is successfully copied, maybe the same method can be used?

**Comment by totebo** [comment]
Would still be good to complete the Mac/PC export.

**Comment by mokalux** [comment]
This may be of help for windows users, even if it does not fix the bug.

Have you tried resource hacker?

http://www.angusj.com/resourcehacker/

I use it myself to change .exe icon when an engine fails short.

**Comment by mokalux** [comment]
As far as i know this is quite complicated to change an .exe icon due to windows restrictions and icon size and operating system and so.

**Comment by totebo** [comment]
Since the Gideros icon is used, and works great, I was hoping to simply replace that with a custom icon.

**Comment by mokalux** [comment]
for icons I had to follow a tutorial on creating icons with GIMP then I used the above mentioned program and voilà. Sometimes you have to take shortcuts so you can carry on releasing a game or an app. Devs are doing the best they can and we try to help them as well.

**Comment by mokalux** [comment]
Icon not exported for Windows has been fixed for quite some time now.
I don't know the status for macOS.

We may close this issue?

**Comment by hgy29** [comment]
It  is still not exported for QT based exports (at least macOS). But using Apple/mac export it works fine. Since there are alternatives to QT for all platforms (except for a few plugins), we may close this issue I think.
